### ISSUE TITLE
there are some bug when I copy image and save image 

### ISSUE THREAD

**Issue by yyf1994gggg** [LulumiProject/lulumi-browser#41] opened 2018-05-08 03:12 UTC
when I  copy image , new Iamge() throw a CROS error.  and "save image "  function  does work. And I find a solution  in brave-broswer project. maybe it can help you 

https://electronjs.org/docs/api/web-contents#contentscopyimageatx-y

https://electronjs.org/docs/api/web-contents#contentscopyimageatx-y

**Comment by qazbnm456** [comment] 2018-05-08 03:25
Hi @yyf1994gggg , thanks for reporting this and giving me the possible solution. BTW, could you please give me the link that I can reproduce the problem you mentioned? Thank you.

**Comment by yyf1994gggg** [comment] 2018-05-08 07:27
![123](https://user-images.githubusercontent.com/31838744/39743518-b3d67716-52d3-11e8-8acb-ce0f63469f0d.jpg)

the error above appear in development environment ，maybe it will be fine In the production environment

**Comment by qazbnm456** [comment] 2018-05-08 08:02
@yyf1994gggg Okay, I know the problem you're facing exactly. It's because you wanna load images from remote sites, the main BrowserWindow will serve files from `origin: localhost` no matter it's in development or production mode, however.

Therefore, you'll be denied to load any file from remote sites. That is, it violates the CORS rule.

To conclude, the best way to load an image into the BrowserWindow is to host the file from local

**Comment by qazbnm456** [comment] 2018-05-08 08:07
To the explanation aboved, I'm about to close the issue. Please don't be hesitated to ask me to reopen it if you've found another problem. Thank you!

**Closed by qazbnm456** 2018-05-08 08:07 UTC
Labels: question, wontfix
